# Optional donations for WinWG OneClick Server.
# Donations are never required to use, modify, redistribute, or contribute.
custom:
  - https://github.com/KLM-corporation/winwg-oneclick-server/blob/main/docs/DONATE.md
